; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S --passes=complex-deinterleaving -mtriple=thumbv8.1m.main-none-eabi -mattr=+mve,+mve.fp %s -o - | FileCheck %s

target triple = "thumbv8.1m.main-none-eabi"

define i32 @cdotp_i8_rot0(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: define i32 @cdotp_i8_rot0(
; CHECK-SAME: <16 x i8> [[A:%.*]], <16 x i8> [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, %[[ENTRY]] ], [ [[PARTIAL_REDUCE_SUB:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[A_DEINTERLEAVED:%.*]] = call { <8 x i8>, <8 x i8> } @llvm.vector.deinterleave2.v16i8(<16 x i8> [[A]])
; CHECK-NEXT:    [[B_DEINTERLEAVED:%.*]] = call { <8 x i8>, <8 x i8> } @llvm.vector.deinterleave2.v16i8(<16 x i8> [[B]])
; CHECK-NEXT:    [[A_REAL:%.*]] = extractvalue { <8 x i8>, <8 x i8> } [[A_DEINTERLEAVED]], 0
; CHECK-NEXT:    [[A_IMAG:%.*]] = extractvalue { <8 x i8>, <8 x i8> } [[A_DEINTERLEAVED]], 1
; CHECK-NEXT:    [[B_REAL:%.*]] = extractvalue { <8 x i8>, <8 x i8> } [[B_DEINTERLEAVED]], 0
; CHECK-NEXT:    [[B_IMAG:%.*]] = extractvalue { <8 x i8>, <8 x i8> } [[B_DEINTERLEAVED]], 1
; CHECK-NEXT:    [[A_REAL_EXT:%.*]] = sext <8 x i8> [[A_REAL]] to <8 x i32>
; CHECK-NEXT:    [[A_IMAG_EXT:%.*]] = sext <8 x i8> [[A_IMAG]] to <8 x i32>
; CHECK-NEXT:    [[B_REAL_EXT:%.*]] = sext <8 x i8> [[B_REAL]] to <8 x i32>
; CHECK-NEXT:    [[B_IMAG_EXT:%.*]] = sext <8 x i8> [[B_IMAG]] to <8 x i32>
; CHECK-NEXT:    [[REAL_MUL:%.*]] = mul <8 x i32> [[B_REAL_EXT]], [[A_REAL_EXT]]
; CHECK-NEXT:    [[REAL_MUL_REDUCED:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v8i32(<4 x i32> [[VEC_PHI]], <8 x i32> [[REAL_MUL]])
; CHECK-NEXT:    [[IMAG_MUL:%.*]] = mul <8 x i32> [[B_IMAG_EXT]], [[A_IMAG_EXT]]
; CHECK-NEXT:    [[IMAG_MUL_NEG:%.*]] = sub <8 x i32> zeroinitializer, [[IMAG_MUL]]
; CHECK-NEXT:    [[PARTIAL_REDUCE_SUB]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v8i32(<4 x i32> [[REAL_MUL_REDUCED]], <8 x i32> [[IMAG_MUL_NEG]])
; CHECK-NEXT:    br i1 true, label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> [[PARTIAL_REDUCE_SUB]])
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  br label %vector.body

vector.body:
  %vec.phi = phi <4 x i32> [ zeroinitializer, %entry ], [ %partial.reduce.sub, %vector.body ]
  %a.deinterleaved = call { <8 x i8>, <8 x i8> } @llvm.vector.deinterleave2.v16i8(<16 x i8> %a)
  %b.deinterleaved = call { <8 x i8>, <8 x i8> } @llvm.vector.deinterleave2.v16i8(<16 x i8> %b)
  %a.real = extractvalue { <8 x i8>, <8 x i8> } %a.deinterleaved, 0
  %a.imag = extractvalue { <8 x i8>, <8 x i8> } %a.deinterleaved, 1
  %b.real = extractvalue { <8 x i8>, <8 x i8> } %b.deinterleaved, 0
  %b.imag = extractvalue { <8 x i8>, <8 x i8> } %b.deinterleaved, 1
  %a.real.ext = sext <8 x i8> %a.real to <8 x i32>
  %a.imag.ext = sext <8 x i8> %a.imag to <8 x i32>
  %b.real.ext = sext <8 x i8> %b.real to <8 x i32>
  %b.imag.ext = sext <8 x i8> %b.imag to <8 x i32>
  %real.mul = mul <8 x i32> %b.real.ext, %a.real.ext
  %real.mul.reduced = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v8i32(<4 x i32> %vec.phi, <8 x i32> %real.mul)
  %imag.mul = mul <8 x i32> %b.imag.ext, %a.imag.ext
  %imag.mul.neg = sub <8 x i32> zeroinitializer, %imag.mul
  %partial.reduce.sub = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.v8i32(<4 x i32> %real.mul.reduced, <8 x i32> %imag.mul.neg)
  br i1 true, label %middle.block, label %vector.body

middle.block:
  %res = call i32 @llvm.vector.reduce.add.v4i32(<4 x i32> %partial.reduce.sub)
  ret i32 %res
}
