; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 5
; Test for autorelease pool optimizations
; RUN: opt -passes=objc-arc < %s -S | FileCheck %s

declare ptr @llvm.objc.autoreleasePoolPush()
declare void @llvm.objc.autoreleasePoolPop(ptr)
declare ptr @llvm.objc.autorelease(ptr)
declare ptr @llvm.objc.retain(ptr)
declare ptr @create_object()
declare void @use_object(ptr)
declare ptr @object_with_thing()
declare void @opaque_callee()

; Empty autorelease pool should be eliminated
define void @test_empty_pool() {
; CHECK-LABEL: define void @test_empty_pool() {
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Pool with only release should be removed
define void @test_autorelease_to_release() {
; CHECK-LABEL: define void @test_autorelease_to_release() {
; CHECK-NEXT:    [[OBJ:%.*]] = call ptr @create_object()
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ]]) #[[ATTR0:[0-9]+]], !clang.imprecise_release [[META0:![0-9]+]]
; CHECK-NEXT:    ret void
;
  %obj = call ptr @create_object()
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj)
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Pool with autoreleases should not be optimized
define void @test_multiple_autoreleases() {
; CHECK-LABEL: define void @test_multiple_autoreleases() {
; CHECK-NEXT:    [[OBJ1:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[OBJ2:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    call void @use_object(ptr [[OBJ1]])
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @llvm.objc.autorelease(ptr [[OBJ1]])
; CHECK-NEXT:    call void @use_object(ptr [[OBJ2]])
; CHECK-NEXT:    [[TMP2:%.*]] = call ptr @llvm.objc.autorelease(ptr [[OBJ2]])
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[POOL]])
; CHECK-NEXT:    ret void
;
  %obj1 = call ptr @create_object()
  %obj2 = call ptr @create_object()
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @use_object(ptr %obj1)
  call ptr @llvm.objc.autorelease(ptr %obj1)
  call void @use_object(ptr %obj2)
  call ptr @llvm.objc.autorelease(ptr %obj2)
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Pool with calls should not be optimized
define void @test_calls() {
; CHECK-LABEL: define void @test_calls() {
; CHECK-NEXT:    [[POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    [[OBJ1:%.*]] = call ptr @object_with_thing()
; CHECK-NEXT:    call void @use_object(ptr [[OBJ1]])
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[POOL]])
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  %obj1 = call ptr @object_with_thing()
  call void @use_object(ptr %obj1)
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Pool with opaque call should not be optimized
define void @test_opaque_call() {
; CHECK-LABEL: define void @test_opaque_call() {
; CHECK-NEXT:    [[POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    call void @opaque_callee()
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[POOL]])
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @opaque_callee()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Nested empty pools should be eliminated
define void @test_nested_empty_pools() {
; CHECK-LABEL: define void @test_nested_empty_pools() {
; CHECK-NEXT:    ret void
;
  %pool1 = call ptr @llvm.objc.autoreleasePoolPush()
  %pool2 = call ptr @llvm.objc.autoreleasePoolPush()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool2)
  call void @llvm.objc.autoreleasePoolPop(ptr %pool1)
  ret void
}

; Empty pool with cast should be eliminated
define void @test_empty_pool_with_cast() {
; CHECK-LABEL: define void @test_empty_pool_with_cast() {
; CHECK-NEXT:    [[CAST:%.*]] = bitcast ptr poison to ptr
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  %cast = bitcast ptr %pool to ptr
  call void @llvm.objc.autoreleasePoolPop(ptr %cast)
  ret void
}

; Autorelease shadowing - autorelease in inner pool doesn't prevent outer optimization
define void @test_autorelease_shadowing_basic() {
; CHECK-LABEL: define void @test_autorelease_shadowing_basic() {
; CHECK-NEXT:    [[OBJ:%.*]] = call ptr @create_object()
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    ret void
;
  %obj = call ptr @create_object()
  %outer_pool = call ptr @llvm.objc.autoreleasePoolPush()

  ; Inner pool with autorelease - this should be shadowed
  %inner_pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner_pool)

  call void @llvm.objc.autoreleasePoolPop(ptr %outer_pool)
  ret void
}

; Multiple nested levels with shadowing
define void @test_multiple_nested_shadowing() {
; CHECK-LABEL: define void @test_multiple_nested_shadowing() {
; CHECK-NEXT:    [[OBJ1:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[OBJ2:%.*]] = call ptr @create_object()
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ1]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ2]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    ret void
;
  %obj1 = call ptr @create_object()
  %obj2 = call ptr @create_object()
  %outer_pool = call ptr @llvm.objc.autoreleasePoolPush()

  ; First inner pool
  %inner1_pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj1)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner1_pool)

  ; Second inner pool with nested level
  %inner2_pool = call ptr @llvm.objc.autoreleasePoolPush()
  %inner3_pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj2)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner3_pool)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner2_pool)

  call void @llvm.objc.autoreleasePoolPop(ptr %outer_pool)
  ret void
}

; Autorelease outside inner pool prevents optimization
define void @test_autorelease_outside_inner_pool() {
; CHECK-LABEL: define void @test_autorelease_outside_inner_pool() {
; CHECK-NEXT:    [[OBJ1:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[OBJ2:%.*]] = call ptr @create_object()
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ1]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ2]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    ret void
;
  %obj1 = call ptr @create_object()
  %obj2 = call ptr @create_object()
  %outer_pool = call ptr @llvm.objc.autoreleasePoolPush()

  ; This autorelease is NOT in an inner pool, so outer pool can't be optimized
  call ptr @llvm.objc.autorelease(ptr %obj1)

  ; Inner pool with autorelease (shadowed)
  %inner_pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj2)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner_pool)

  call void @llvm.objc.autoreleasePoolPop(ptr %outer_pool)
  ret void
}

; Known ObjC functions don't prevent optimization
define void @test_known_objc_functions() {
; CHECK-LABEL: define void @test_known_objc_functions() {
; CHECK-NEXT:    [[OBJ:%.*]] = call ptr @create_object()
; CHECK-NEXT:    ret void
;
  %obj = call ptr @create_object()
  %pool = call ptr @llvm.objc.autoreleasePoolPush()

  ; These are all known ObjC runtime functions that don't produce autoreleases
  %retained = call ptr @llvm.objc.retain(ptr %obj)
  call void @llvm.objc.release(ptr %obj)

  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Complex shadowing with mixed autoreleases
define void @test_complex_shadowing() {
; CHECK-LABEL: define void @test_complex_shadowing() {
; CHECK-NEXT:    [[OBJ1:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[OBJ2:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[OBJ3:%.*]] = call ptr @create_object()
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ1]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ2]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    [[INNER2_POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @llvm.objc.autorelease(ptr [[OBJ3]])
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[INNER2_POOL]])
; CHECK-NEXT:    ret void
;
  %obj1 = call ptr @create_object()
  %obj2 = call ptr @create_object()
  %obj3 = call ptr @create_object()
  %outer_pool = call ptr @llvm.objc.autoreleasePoolPush()

  ; This autorelease is outside inner pools - prevents optimization
  call ptr @llvm.objc.autorelease(ptr %obj1)

  ; Inner pool 1 with shadowed autorelease
  %inner1_pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj2)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner1_pool)

  ; Some safe ObjC operations
  %retained = call ptr @llvm.objc.retain(ptr %obj3)
  call void @llvm.objc.release(ptr %retained)

  ; Inner pool 2 with shadowed autorelease
  %inner2_pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj3)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner2_pool)

  call void @llvm.objc.autoreleasePoolPop(ptr %outer_pool)
  ret void
}

; Non-ObjC function that may autorelease prevents optimization
define void @test_non_objc_may_autorelease() {
; CHECK-LABEL: define void @test_non_objc_may_autorelease() {
; CHECK-NEXT:    [[POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    [[TMP1:%.*]] = call ptr @function_that_might_autorelease()
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[POOL]])
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @function_that_might_autorelease()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Non-ObjC function that doesn't autorelease allows optimization
define void @test_non_objc_no_autorelease() {
; CHECK-LABEL: define void @test_non_objc_no_autorelease() {
; CHECK-NEXT:    call void @safe_function()
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @safe_function()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

; Incomplete push/pop pairs across blocks - only inner pairs count
define void @test_incomplete_pairs_inner_shadowing() {
; CHECK-LABEL: define void @test_incomplete_pairs_inner_shadowing() {
; CHECK-NEXT:    [[OBJ:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[OUTER_POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    ret void
;
  %obj = call ptr @create_object()
  %outer_pool = call ptr @llvm.objc.autoreleasePoolPush()

  ; Inner complete pair - autorelease should be shadowed by this
  %inner_pool = call ptr @llvm.objc.autoreleasePoolPush()
  call ptr @llvm.objc.autorelease(ptr %obj)      ; This SHOULD be shadowed by inner pair
  call void @llvm.objc.autoreleasePoolPop(ptr %inner_pool)  ; Completes the inner pair

  ; Note: %outer_pool pop is in a different block (common pattern)
  ; But the autorelease was shadowed by the complete inner pair
  ret void
}

; Helper functions for testing interprocedural analysis

; Safe function that doesn't call autorelease
define void @safe_function() {
  ; Just some computation, no autoreleases
; CHECK-LABEL: define void @safe_function() {
; CHECK-NEXT:    [[X:%.*]] = add i32 1, 2
; CHECK-NEXT:    ret void
;
  %x = add i32 1, 2
  ret void
}

; Function that may produce autoreleases (simulated by calling autorelease)
define ptr @function_that_might_autorelease() {
; CHECK-LABEL: define ptr @function_that_might_autorelease() {
; CHECK-NEXT:    [[OBJ:%.*]] = call ptr @create_object()
; CHECK-NEXT:    [[AUTORELEASED:%.*]] = call ptr @llvm.objc.autorelease(ptr [[OBJ]])
; CHECK-NEXT:    ret ptr [[AUTORELEASED]]
;
  %obj = call ptr @create_object()
  %autoreleased = call ptr @llvm.objc.autorelease(ptr %obj)
  ret ptr %autoreleased
}

; Cross-function: callee has its own inner pool containing an autorelease.
; The caller's pool should be optimizable since the callee's autorelease
; is contained within the callee's own pool.
define void @test_cross_function_inner_pool_caller() {
; CHECK-LABEL: define void @test_cross_function_inner_pool_caller() {
; CHECK-NEXT:    call void @test_cross_function_inner_pool_callee()
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @test_cross_function_inner_pool_callee()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

define void @test_cross_function_inner_pool_callee() {
; CHECK-LABEL: define void @test_cross_function_inner_pool_callee() {
; CHECK-NEXT:    [[INNER_POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    [[OBJ:%.*]] = call ptr @create_object()
; CHECK-NEXT:    call void @llvm.objc.release(ptr [[OBJ]]) #[[ATTR0]], !clang.imprecise_release [[META0]]
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[INNER_POOL]])
; CHECK-NEXT:    ret void
;
  %inner_pool = call ptr @llvm.objc.autoreleasePoolPush()
  %obj = call ptr @create_object()
  %ar = call ptr @llvm.objc.autorelease(ptr %obj)
  call void @llvm.objc.autoreleasePoolPop(ptr %inner_pool)
  ret void
}

; Cross-block in callee: push/call/pop split across blocks.
; The potential autorelease is contained by callee pool, so caller pool should
; be eliminated.
define void @test_cross_block_callee_pool_contains_call_caller() {
; CHECK-LABEL: define void @test_cross_block_callee_pool_contains_call_caller() {
; CHECK-NEXT:    [[POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    call void @cross_block_callee_pool_contains_call()
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[POOL]])
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @cross_block_callee_pool_contains_call()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

define void @cross_block_callee_pool_contains_call() {
; CHECK-LABEL: define void @cross_block_callee_pool_contains_call() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    br label %[[MID:.*]]
; CHECK:       [[MID]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @function_that_might_autorelease()
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[P]])
; CHECK-NEXT:    ret void
;
entry:
  %p = call ptr @llvm.objc.autoreleasePoolPush()
  br label %mid

mid:
  call ptr @function_that_might_autorelease()
  br label %exit

exit:
  call void @llvm.objc.autoreleasePoolPop(ptr %p)
  ret void
}

; Cross-block in callee with nested pools around call.
; The nested call should remain contained and caller pool should be eliminated.
define void @test_cross_block_callee_nested_pool_contains_call_caller() {
; CHECK-LABEL: define void @test_cross_block_callee_nested_pool_contains_call_caller() {
; CHECK-NEXT:    [[POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    call void @cross_block_callee_nested_pool_contains_call()
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[POOL]])
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @cross_block_callee_nested_pool_contains_call()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

define void @cross_block_callee_nested_pool_contains_call() {
; CHECK-LABEL: define void @cross_block_callee_nested_pool_contains_call() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[OUTER:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    br label %[[INNER_PUSH:.*]]
; CHECK:       [[INNER_PUSH]]:
; CHECK-NEXT:    [[INNER:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    br label %[[CALL_BLOCK:.*]]
; CHECK:       [[CALL_BLOCK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @function_that_might_autorelease()
; CHECK-NEXT:    br label %[[INNER_POP:.*]]
; CHECK:       [[INNER_POP]]:
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[INNER]])
; CHECK-NEXT:    br label %[[OUTER_POP:.*]]
; CHECK:       [[OUTER_POP]]:
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[OUTER]])
; CHECK-NEXT:    ret void
;
entry:
  %outer = call ptr @llvm.objc.autoreleasePoolPush()
  br label %inner_push

inner_push:
  %inner = call ptr @llvm.objc.autoreleasePoolPush()
  br label %call_block

call_block:
  call ptr @function_that_might_autorelease()
  br label %inner_pop

inner_pop:
  call void @llvm.objc.autoreleasePoolPop(ptr %inner)
  br label %outer_pop

outer_pop:
  call void @llvm.objc.autoreleasePoolPop(ptr %outer)
  ret void
}

; Cross-block in callee: push/pop close before call, so call escapes pool.
; Caller pool must not be eliminated.
define void @test_cross_block_callee_call_after_pop_caller() {
; CHECK-LABEL: define void @test_cross_block_callee_call_after_pop_caller() {
; CHECK-NEXT:    [[POOL:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    call void @cross_block_callee_call_after_pop()
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[POOL]])
; CHECK-NEXT:    ret void
;
  %pool = call ptr @llvm.objc.autoreleasePoolPush()
  call void @cross_block_callee_call_after_pop()
  call void @llvm.objc.autoreleasePoolPop(ptr %pool)
  ret void
}

define void @cross_block_callee_call_after_pop() {
; CHECK-LABEL: define void @cross_block_callee_call_after_pop() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = call ptr @llvm.objc.autoreleasePoolPush()
; CHECK-NEXT:    br label %[[POP_BLOCK:.*]]
; CHECK:       [[POP_BLOCK]]:
; CHECK-NEXT:    call void @llvm.objc.autoreleasePoolPop(ptr [[P]])
; CHECK-NEXT:    br label %[[CALL_BLOCK:.*]]
; CHECK:       [[CALL_BLOCK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @function_that_might_autorelease()
; CHECK-NEXT:    ret void
;
entry:
  %p = call ptr @llvm.objc.autoreleasePoolPush()
  br label %pop_block

pop_block:
  call void @llvm.objc.autoreleasePoolPop(ptr %p)
  br label %call_block

call_block:
  call ptr @function_that_might_autorelease()
  ret void
}

;.
; CHECK: [[META0]] = !{}
;.
