; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 < %s | FileCheck %s

; This test ensures that the DAGCombiner doesn't get stuck in an infinite loop
; between RISCVISelLowering converting (X & 0xFFFFFFFF) == C to sext_inreg
; and DAGCombiner converting sext_inreg back to AND.

define i64 @reproduce(i1 %0) {
; CHECK-LABEL: reproduce:
; CHECK:       # %bb.0:
; CHECK:         ret
  %2 = select i1 %0, i64 44587060572238, i64 0
  %3 = and i64 %2, 1005072462
  %4 = icmp eq i64 %3, 0
  %5 = zext i1 %4 to i64
  %6 = or i64 %2, %5
  ret i64 %6
}
