; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-none-linux-gnu < %s | FileCheck %s

define i32 @add_cmp_f32(float %a, float %b, i32 %c) {
; CHECK-LABEL: add_cmp_f32:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    cinc w0, w0, eq
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp oeq float %a, %b
  %conv = zext i1 %cmp to i32
  %add = add i32 %c, %conv
  ret i32 %add
}

define i64 @add_cmp_f64(double %a, double %b, i64 %c) {
; CHECK-LABEL: add_cmp_f64:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmp d0, d1
; CHECK-NEXT:    cinc x0, x0, mi
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp olt double %a, %b
  %conv = zext i1 %cmp to i64
  %add = add i64 %c, %conv
  ret i64 %add
}

define i32 @add_cmp_f32_uge(float %a, float %b, i32 %c) {
; CHECK-LABEL: add_cmp_f32_uge:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    cinc w0, w0, pl
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp uge float %a, %b
  %conv = zext i1 %cmp to i32
  %add = add i32 %c, %conv
  ret i32 %add
}

; Fallback for dual-CC
define i32 @add_cmp_f32_one(float %a, float %b, i32 %c) {
; CHECK-LABEL: add_cmp_f32_one:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmp s0, s1
; CHECK-NEXT:    cset w8, mi
; CHECK-NEXT:    csinc w8, w8, wzr, le
; CHECK-NEXT:    add w0, w0, w8
; CHECK-NEXT:    ret
entry:
  %cmp = fcmp one float %a, %b
  %conv = zext i1 %cmp to i32
  %add = add i32 %c, %conv
  ret i32 %add
}
