; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -fast-isel=0 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ISEL
; RUN: llc -mtriple=aarch64-linux-gnu -fast-isel=1 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,FAST

define i32 @test1(i32 %x) {
; CHECK-LABEL: test1:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add w8, w0, #7
; CHECK-NEXT:    cmp w0, #0
; CHECK-NEXT:    csel w8, w8, w0, lt
; CHECK-NEXT:    asr w0, w8, #3
; CHECK-NEXT:    ret
  %div = sdiv i32 %x, 8
  ret i32 %div
}

define i32 @test1_exact(i32 %x) {
; CHECK-LABEL: test1_exact:
; CHECK:       // %bb.0:
; CHECK-NEXT:    asr w0, w0, #3
; CHECK-NEXT:    ret
  %div = sdiv exact i32 %x, 8
  ret i32 %div
}

define i32 @test2(i32 %x) {
; CHECK-LABEL: test2:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add w8, w0, #7
; CHECK-NEXT:    cmp w0, #0
; CHECK-NEXT:    csel w8, w8, w0, lt
; CHECK-NEXT:    neg w0, w8, asr #3
; CHECK-NEXT:    ret
  %div = sdiv i32 %x, -8
  ret i32 %div
}

define i32 @test2_exact(i32 %x) {
; ISEL-LABEL: test2_exact:
; ISEL:       // %bb.0:
; ISEL-NEXT:    neg w0, w0, asr #3
; ISEL-NEXT:    ret
;
; FAST-LABEL: test2_exact:
; FAST:       // %bb.0:
; FAST-NEXT:    asr w0, w0, #3
; FAST-NEXT:    ret
  %div = sdiv exact i32 %x, -8
  ret i32 %div
}

define i32 @test3(i32 %x) {
; CHECK-LABEL: test3:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add w8, w0, #31
; CHECK-NEXT:    cmp w0, #0
; CHECK-NEXT:    csel w8, w8, w0, lt
; CHECK-NEXT:    asr w0, w8, #5
; CHECK-NEXT:    ret
  %div = sdiv i32 %x, 32
  ret i32 %div
}

define i32 @test3_exact(i32 %x) {
; CHECK-LABEL: test3_exact:
; CHECK:       // %bb.0:
; CHECK-NEXT:    asr w0, w0, #5
; CHECK-NEXT:    ret
  %div = sdiv exact i32 %x, 32
  ret i32 %div
}

define i64 @test4(i64 %x) {
; CHECK-LABEL: test4:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add x8, x0, #7
; CHECK-NEXT:    cmp x0, #0
; CHECK-NEXT:    csel x8, x8, x0, lt
; CHECK-NEXT:    asr x0, x8, #3
; CHECK-NEXT:    ret
  %div = sdiv i64 %x, 8
  ret i64 %div
}

define i64 @test4_exact(i64 %x) {
; CHECK-LABEL: test4_exact:
; CHECK:       // %bb.0:
; CHECK-NEXT:    asr x0, x0, #3
; CHECK-NEXT:    ret
  %div = sdiv exact i64 %x, 8
  ret i64 %div
}

define i64 @test5(i64 %x) {
; CHECK-LABEL: test5:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add x8, x0, #7
; CHECK-NEXT:    cmp x0, #0
; CHECK-NEXT:    csel x8, x8, x0, lt
; CHECK-NEXT:    neg x0, x8, asr #3
; CHECK-NEXT:    ret
  %div = sdiv i64 %x, -8
  ret i64 %div
}

define i64 @test5_exact(i64 %x) {
; ISEL-LABEL: test5_exact:
; ISEL:       // %bb.0:
; ISEL-NEXT:    neg x0, x0, asr #3
; ISEL-NEXT:    ret
;
; FAST-LABEL: test5_exact:
; FAST:       // %bb.0:
; FAST-NEXT:    asr x0, x0, #3
; FAST-NEXT:    ret
  %div = sdiv exact i64 %x, -8
  ret i64 %div
}

define i64 @test6(i64 %x) {
; CHECK-LABEL: test6:
; CHECK:       // %bb.0:
; CHECK-NEXT:    add x8, x0, #63
; CHECK-NEXT:    cmp x0, #0
; CHECK-NEXT:    csel x8, x8, x0, lt
; CHECK-NEXT:    asr x0, x8, #6
; CHECK-NEXT:    ret
  %div = sdiv i64 %x, 64
  ret i64 %div
}

define i64 @test6_exact(i64 %x) {
; CHECK-LABEL: test6_exact:
; CHECK:       // %bb.0:
; CHECK-NEXT:    asr x0, x0, #6
; CHECK-NEXT:    ret
  %div = sdiv exact i64 %x, 64
  ret i64 %div
}

define i64 @test7(i64 %x) {
; CHECK-LABEL: test7:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov x8, #281474976710655 // =0xffffffffffff
; CHECK-NEXT:    cmp x0, #0
; CHECK-NEXT:    add x8, x0, x8
; CHECK-NEXT:    csel x8, x8, x0, lt
; CHECK-NEXT:    asr x0, x8, #48
; CHECK-NEXT:    ret
  %div = sdiv i64 %x, 281474976710656
  ret i64 %div
}

define i64 @test7_exact(i64 %x) {
; CHECK-LABEL: test7_exact:
; CHECK:       // %bb.0:
; CHECK-NEXT:    asr x0, x0, #48
; CHECK-NEXT:    ret
  %div = sdiv exact i64 %x, 281474976710656
  ret i64 %div
}

define i64 @test8(i64 %x) {
; ISEL-LABEL: test8:
; ISEL:       // %bb.0:
; ISEL-NEXT:    add x8, x0, x0, lsr #63
; ISEL-NEXT:    asr x0, x8, #1
; ISEL-NEXT:    ret
;
; FAST-LABEL: test8:
; FAST:       // %bb.0:
; FAST-NEXT:    add x8, x0, #1
; FAST-NEXT:    cmp x0, #0
; FAST-NEXT:    csel x8, x8, x0, lt
; FAST-NEXT:    asr x0, x8, #1
; FAST-NEXT:    ret
  %div = sdiv i64 %x, 2
  ret i64 %div
}

define i64 @test8_exact(i64 %x) {
; CHECK-LABEL: test8_exact:
; CHECK:       // %bb.0:
; CHECK-NEXT:    asr x0, x0, #1
; CHECK-NEXT:    ret
  %div = sdiv exact i64 %x, 2
  ret i64 %div
}

define i32 @sdiv_int(i32 %begin, i32 %first) #0 {
; ISEL-LABEL: sdiv_int:
; ISEL:       // %bb.0:
; ISEL-NEXT:    sub w8, w0, w1
; ISEL-NEXT:    add w8, w8, #1
; ISEL-NEXT:    add w8, w8, w8, lsr #31
; ISEL-NEXT:    sub w0, w0, w8, asr #1
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_int:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #1
; FAST-NEXT:    sub w8, w8, w1
; FAST-NEXT:    add w9, w8, #1
; FAST-NEXT:    cmp w8, #0
; FAST-NEXT:    csel w8, w9, w8, lt
; FAST-NEXT:    neg w8, w8, asr #1
; FAST-NEXT:    add w0, w8, w0
; FAST-NEXT:    ret
  %sub = add i32 %begin, 1
  %add = sub i32 %sub, %first
  %div.neg = sdiv i32 %add, -2
  %sub1 = add i32 %div.neg, %begin
  ret i32 %sub1
}

define i32 @sdiv_int_exact(i32 %begin, i32 %first) #0 {
; ISEL-LABEL: sdiv_int_exact:
; ISEL:       // %bb.0:
; ISEL-NEXT:    sub w8, w0, w1
; ISEL-NEXT:    add w8, w8, #1
; ISEL-NEXT:    sub w0, w0, w8, asr #1
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_int_exact:
; FAST:       // %bb.0:
; FAST-NEXT:    add w8, w0, #1
; FAST-NEXT:    sub w8, w8, w1
; FAST-NEXT:    asr w8, w8, #1
; FAST-NEXT:    add w0, w8, w0
; FAST-NEXT:    ret
  %sub = add i32 %begin, 1
  %add = sub i32 %sub, %first
  %div.neg = sdiv exact i32 %add, -2
  %sub1 = add i32 %div.neg, %begin
  ret i32 %sub1
}

define i32 @sdiv_no_2(i32 %x) {
; ISEL-LABEL: sdiv_no_2:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov w8, #9363 // =0x2493
; ISEL-NEXT:    movk w8, #37449, lsl #16
; ISEL-NEXT:    smull x8, w0, w8
; ISEL-NEXT:    lsr x8, x8, #32
; ISEL-NEXT:    add w8, w8, w0
; ISEL-NEXT:    asr w9, w8, #2
; ISEL-NEXT:    add w0, w9, w8, lsr #31
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_no_2:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #7 // =0x7
; FAST-NEXT:    sdiv w0, w0, w8
; FAST-NEXT:    ret
    %div = sdiv i32 %x, 7
    ret i32 %div
}

define i64 @sdiv_no_2_64(i64 %x) {
; ISEL-LABEL: sdiv_no_2_64:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov x8, #18725 // =0x4925
; ISEL-NEXT:    movk x8, #9362, lsl #16
; ISEL-NEXT:    movk x8, #37449, lsl #32
; ISEL-NEXT:    movk x8, #18724, lsl #48
; ISEL-NEXT:    smulh x8, x0, x8
; ISEL-NEXT:    asr x9, x8, #1
; ISEL-NEXT:    add x0, x9, x8, lsr #63
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_no_2_64:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #7 // =0x7
; FAST-NEXT:    sdiv x0, x0, x8
; FAST-NEXT:    ret
    %div = sdiv i64 %x, 7
    ret i64 %div
}

define i32 @sdiv_no_2_exact(i32 %x) {
; ISEL-LABEL: sdiv_no_2_exact:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov w8, #28087 // =0x6db7
; ISEL-NEXT:    movk w8, #46811, lsl #16
; ISEL-NEXT:    mul w0, w0, w8
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_no_2_exact:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #7 // =0x7
; FAST-NEXT:    sdiv w0, w0, w8
; FAST-NEXT:    ret
    %div = sdiv exact i32 %x, 7
    ret i32 %div
}

define i64 @sdiv_no_2_64_exact(i64 %x) {
; ISEL-LABEL: sdiv_no_2_64_exact:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov x8, #28087 // =0x6db7
; ISEL-NEXT:    movk x8, #46811, lsl #16
; ISEL-NEXT:    movk x8, #56173, lsl #32
; ISEL-NEXT:    movk x8, #28086, lsl #48
; ISEL-NEXT:    mul x0, x0, x8
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_no_2_64_exact:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #7 // =0x7
; FAST-NEXT:    sdiv x0, x0, x8
; FAST-NEXT:    ret
    %div = sdiv exact i64 %x, 7
    ret i64 %div
}

define i64 @sdiv_no_2_64_d(i64 %x) {
; ISEL-LABEL: sdiv_no_2_64_d:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov x8, #49933 // =0xc30d
; ISEL-NEXT:    movk x8, #3120, lsl #16
; ISEL-NEXT:    movk x8, #12483, lsl #32
; ISEL-NEXT:    movk x8, #49932, lsl #48
; ISEL-NEXT:    smulh x8, x0, x8
; ISEL-NEXT:    add x8, x8, x0
; ISEL-NEXT:    asr x9, x8, #5
; ISEL-NEXT:    add x0, x9, x8, lsr #63
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_no_2_64_d:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #42 // =0x2a
; FAST-NEXT:    sdiv x0, x0, x8
; FAST-NEXT:    ret
    %div = sdiv i64 %x, 42
    ret i64 %div
}

define i64 @sdiv_no_2_64_exact_d(i64 %x) {
; ISEL-LABEL: sdiv_no_2_64_exact_d:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov x9, #53053 // =0xcf3d
; ISEL-NEXT:    asr x8, x0, #1
; ISEL-NEXT:    movk x9, #15603, lsl #16
; ISEL-NEXT:    movk x9, #62415, lsl #32
; ISEL-NEXT:    movk x9, #53052, lsl #48
; ISEL-NEXT:    mul x0, x8, x9
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_no_2_64_exact_d:
; FAST:       // %bb.0:
; FAST-NEXT:    mov x8, #42 // =0x2a
; FAST-NEXT:    sdiv x0, x0, x8
; FAST-NEXT:    ret
    %div = sdiv exact i64 %x, 42
    ret i64 %div
}

define i32 @sdiv_no_2_exact_ooh(i32 %x) {
; ISEL-LABEL: sdiv_no_2_exact_ooh:
; ISEL:       // %bb.0:
; ISEL-NEXT:    mov w8, #48771 // =0xbe83
; ISEL-NEXT:    movk w8, #12192, lsl #16
; ISEL-NEXT:    mul w0, w0, w8
; ISEL-NEXT:    ret
;
; FAST-LABEL: sdiv_no_2_exact_ooh:
; FAST:       // %bb.0:
; FAST-NEXT:    mov w8, #43 // =0x2b
; FAST-NEXT:    sdiv w0, w0, w8
; FAST-NEXT:    ret
    %div = sdiv exact i32 %x, 43
    ret i32 %div
}

define <4 x i16> @what(<4 x i16> %x)
; CHECK-LABEL: what:
; CHECK:       // %bb.0:
; CHECK-NEXT:    adrp x8, .LCPI25_0
; CHECK-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-NEXT:    ldr d1, [x8, :lo12:.LCPI25_0]
; CHECK-NEXT:    adrp x8, .LCPI25_1
; CHECK-NEXT:    smull v1.4s, v0.4h, v1.4h
; CHECK-NEXT:    mov v0.s[0], wzr
; CHECK-NEXT:    shrn v1.4h, v1.4s, #16
; CHECK-NEXT:    add v0.4h, v1.4h, v0.4h
; CHECK-NEXT:    ldr d1, [x8, :lo12:.LCPI25_1]
; CHECK-NEXT:    sshl v0.4h, v0.4h, v1.4h
; CHECK-NEXT:    usra v0.4h, v0.4h, #15
; CHECK-NEXT:    ret
{
    %V4i16 = sdiv <4 x i16> %x, <i16 9, i16 9, i16 21, i16 16>
    ret <4 x i16> %V4i16
}

define <vscale x 4 x i32> @sdiv_i64_neg(<vscale x 4 x i32> %a) #0 {
; CHECK-LABEL: sdiv_i64_neg:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #31711 // =0x7bdf
; CHECK-NEXT:    ptrue p0.s
; CHECK-NEXT:    movk w8, #48623, lsl #16
; CHECK-NEXT:    mov z1.s, w8
; CHECK-NEXT:    mul z0.s, p0/m, z0.s, z1.s
; CHECK-NEXT:    ret
  %out = sdiv exact <vscale x 4 x i32> %a, splat(i32 31)
  ret <vscale x 4 x i32> %out
}

attributes #0 = { "target-features"="+sve" vscale_range(2,2) }
