; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define i32 @test_smin_umin(i32 %s, i32 %p) {
; CHECK-LABEL: @test_smin_umin(
; CHECK-NEXT:    [[IS_POS:%.*]] = icmp sgt i32 [[P:%.*]], -1
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_POS]])
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.umin.i32(i32 [[S:%.*]], i32 [[P]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %is_pos = icmp sgt i32 %p, -1
  call void @llvm.assume(i1 %is_pos)
  %min = call i32 @llvm.smin.i32(i32 %s, i32 %p)
  %is_neg = icmp slt i32 %s, 0
  %res = select i1 %is_neg, i32 %p, i32 %min
  ret i32 %res
}

define i32 @test_smin_umin_swapped(i32 %s, i32 %p) {
; CHECK-LABEL: @test_smin_umin_swapped(
; CHECK-NEXT:    [[IS_POS:%.*]] = icmp sgt i32 [[P:%.*]], -1
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_POS]])
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.umin.i32(i32 [[S:%.*]], i32 [[P]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %is_pos = icmp sgt i32 %p, -1
  call void @llvm.assume(i1 %is_pos)
  %min = call i32 @llvm.smin.i32(i32 %s, i32 %p)
  %is_pos_s1 = icmp sgt i32 %s, -1
  %res = select i1 %is_pos_s1, i32 %min, i32 %p
  ret i32 %res
}

define i32 @test_smax_umax(i32 %s, i32 %n) {
; CHECK-LABEL: @test_smax_umax(
; CHECK-NEXT:    [[IS_NEG_N:%.*]] = icmp slt i32 [[N:%.*]], 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_NEG_N]])
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.umax.i32(i32 [[S:%.*]], i32 [[N]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %is_neg_n = icmp sle i32 %n, 0
  call void @llvm.assume(i1 %is_neg_n)
  %max = call i32 @llvm.smax.i32(i32 %s, i32 %n)
  %is_neg_s = icmp slt i32 %s, 0
  %res = select i1 %is_neg_s, i32 %max, i32 %n
  ret i32 %res
}

define i32 @test_smax_umax_swapped(i32 %s, i32 %n) {
; CHECK-LABEL: @test_smax_umax_swapped(
; CHECK-NEXT:    [[IS_NEG_N:%.*]] = icmp slt i32 [[N:%.*]], 1
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_NEG_N]])
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.umax.i32(i32 [[S:%.*]], i32 [[N]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %is_neg_n = icmp sle i32 %n, 0
  call void @llvm.assume(i1 %is_neg_n)
  %max = call i32 @llvm.smax.i32(i32 %s, i32 %n)
  %is_pos_s1 = icmp sgt i32 %s, -1
  %res = select i1 %is_pos_s1, i32 %n, i32 %max
  ret i32 %res
}

declare void @llvm.assume(i1)
declare i32 @llvm.smin.i32(i32, i32)
declare i32 @llvm.smax.i32(i32, i32)
