; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=-popcnt | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=-popcnt | FileCheck %s --check-prefix=X64

; Test that parity of the low byte folds into the producing arithmetic op's
; parity flag, eliminating a redundant TEST.

define i32 @parity_of_add_i8(i32 %a, i32 %b, ptr %out) nounwind {
; X86-LABEL: parity_of_add_i8:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    addl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setnp (%ecx)
; X86-NEXT:    retl
;
; X64-LABEL: parity_of_add_i8:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    addl %esi, %eax
; X64-NEXT:    setnp (%rdx)
; X64-NEXT:    retq
  %add = add i32 %a, %b
  %trunc = trunc i32 %add to i8
  %pop = call i8 @llvm.ctpop.i8(i8 %trunc)
  %par = and i8 %pop, 1
  store i8 %par, ptr %out
  ret i32 %add
}

define i32 @parity_of_sub_i8(i32 %a, i32 %b, ptr %out) nounwind {
; X86-LABEL: parity_of_sub_i8:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    subl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setnp (%ecx)
; X86-NEXT:    retl
;
; X64-LABEL: parity_of_sub_i8:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    subl %esi, %eax
; X64-NEXT:    setnp (%rdx)
; X64-NEXT:    retq
  %sub = sub i32 %a, %b
  %trunc = trunc i32 %sub to i8
  %pop = call i8 @llvm.ctpop.i8(i8 %trunc)
  %par = and i8 %pop, 1
  store i8 %par, ptr %out
  ret i32 %sub
}

define i32 @parity_of_xor_i8(i32 %a, i32 %b, ptr %out) nounwind {
; X86-LABEL: parity_of_xor_i8:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    xorl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setnp (%ecx)
; X86-NEXT:    retl
;
; X64-LABEL: parity_of_xor_i8:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    xorl %esi, %eax
; X64-NEXT:    setnp (%rdx)
; X64-NEXT:    retq
  %xor = xor i32 %a, %b
  %trunc = trunc i32 %xor to i8
  %pop = call i8 @llvm.ctpop.i8(i8 %trunc)
  %par = and i8 %pop, 1
  store i8 %par, ptr %out
  ret i32 %xor
}

define i32 @parity_of_and_i8(i32 %a, i32 %b, ptr %out) nounwind {
; X86-LABEL: parity_of_and_i8:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    andl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setnp (%ecx)
; X86-NEXT:    retl
;
; X64-LABEL: parity_of_and_i8:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    andl %esi, %eax
; X64-NEXT:    setnp (%rdx)
; X64-NEXT:    retq
  %and = and i32 %a, %b
  %trunc = trunc i32 %and to i8
  %pop = call i8 @llvm.ctpop.i8(i8 %trunc)
  %par = and i8 %pop, 1
  store i8 %par, ptr %out
  ret i32 %and
}

define i32 @parity_of_or_i8(i32 %a, i32 %b, ptr %out) nounwind {
; X86-LABEL: parity_of_or_i8:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    orl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setnp (%ecx)
; X86-NEXT:    retl
;
; X64-LABEL: parity_of_or_i8:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    orl %esi, %eax
; X64-NEXT:    setnp (%rdx)
; X64-NEXT:    retq
  %or = or i32 %a, %b
  %trunc = trunc i32 %or to i8
  %pop = call i8 @llvm.ctpop.i8(i8 %trunc)
  %par = and i8 %pop, 1
  store i8 %par, ptr %out
  ret i32 %or
}

; Parity standalone (no multi-use of the arith result) - should also fold
define i8 @parity_of_add_standalone(i8 %a, i8 %b) nounwind {
; X86-LABEL: parity_of_add_standalone:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    addb {{[0-9]+}}(%esp), %al
; X86-NEXT:    setnp %al
; X86-NEXT:    retl
;
; X64-LABEL: parity_of_add_standalone:
; X64:       # %bb.0:
; X64-NEXT:    addb %sil, %dil
; X64-NEXT:    setnp %al
; X64-NEXT:    retq
  %add = add i8 %a, %b
  %pop = call i8 @llvm.ctpop.i8(i8 %add)
  %par = and i8 %pop, 1
  ret i8 %par
}

; Negative test: parity of full i32 value (not just low byte)
define i32 @parity_of_add_i32(i32 %a, i32 %b, ptr %out) nounwind {
; X86-LABEL: parity_of_add_i32:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    addl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl %eax, %edx
; X86-NEXT:    shrl $16, %edx
; X86-NEXT:    xorl %eax, %edx
; X86-NEXT:    xorl %ebx, %ebx
; X86-NEXT:    xorb %dh, %dl
; X86-NEXT:    setnp %bl
; X86-NEXT:    movl %ebx, (%ecx)
; X86-NEXT:    popl %ebx
; X86-NEXT:    retl
;
; X64-LABEL: parity_of_add_i32:
; X64:       # %bb.0:
; X64-NEXT:    # kill: def $esi killed $esi def $rsi
; X64-NEXT:    # kill: def $edi killed $edi def $rdi
; X64-NEXT:    leal (%rdi,%rsi), %eax
; X64-NEXT:    movl %eax, %ecx
; X64-NEXT:    shrl $16, %ecx
; X64-NEXT:    xorl %eax, %ecx
; X64-NEXT:    xorl %esi, %esi
; X64-NEXT:    xorb %ch, %cl
; X64-NEXT:    setnp %sil
; X64-NEXT:    movl %esi, (%rdx)
; X64-NEXT:    retq
  %add = add i32 %a, %b
  %pop = call i32 @llvm.ctpop.i32(i32 %add)
  %par = and i32 %pop, 1
  store i32 %par, ptr %out
  ret i32 %add
}
