; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=i686-unknown-unknown | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s --check-prefix=X64

define i32 @shl_test_bit_to_parity(i32 %a, i32 %b) nounwind {
; X86-LABEL: shl_test_bit_to_parity:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shll $7, %eax
; X86-NEXT:    testb %al, %al
; X86-NEXT:    js .LBB0_2
; X86-NEXT:  # %bb.1:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:  .LBB0_2:
; X86-NEXT:    retl
;
; X64-LABEL: shl_test_bit_to_parity:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    shll $7, %eax
; X64-NEXT:    testb %al, %al
; X64-NEXT:    cmovnsl %esi, %eax
; X64-NEXT:    retq
  %shl = shl i32 %a, 7
  %and = and i32 %shl, 128
  %cmp = icmp ne i32 %and, 0
  %sel = select i1 %cmp, i32 %shl, i32 %b
  ret i32 %sel
}

define i32 @shl_test_bit_to_parity_32(i32 %a, i32 %b) nounwind {
; X86-LABEL: shl_test_bit_to_parity_32:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shll $31, %eax
; X86-NEXT:    jne .LBB1_2
; X86-NEXT:  # %bb.1:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:  .LBB1_2:
; X86-NEXT:    retl
;
; X64-LABEL: shl_test_bit_to_parity_32:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    shll $31, %eax
; X64-NEXT:    cmovel %esi, %eax
; X64-NEXT:    retq
  %shl = shl i32 %a, 31
  %and = and i32 %shl, 2147483648
  %cmp = icmp ne i32 %and, 0
  %sel = select i1 %cmp, i32 %shl, i32 %b
  ret i32 %sel
}

define i32 @shl_test_bit_to_parity_not_7(i32 %a, i32 %b) nounwind {
; X86-LABEL: shl_test_bit_to_parity_not_7:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    testb $1, %al
; X86-NEXT:    jne .LBB2_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    retl
; X86-NEXT:  .LBB2_1:
; X86-NEXT:    shll $6, %eax
; X86-NEXT:    retl
;
; X64-LABEL: shl_test_bit_to_parity_not_7:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, %eax
; X64-NEXT:    shll $6, %eax
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovel %esi, %eax
; X64-NEXT:    retq
  %shl = shl i32 %a, 6
  %and = and i32 %shl, 64
  %cmp = icmp ne i32 %and, 0
  %sel = select i1 %cmp, i32 %shl, i32 %b
  ret i32 %sel
}
